export const tipos_armas = {
    'Arma': [
        {"Tipo": "Adaga", "Subtipo": "Karambit", "DIF": "6 (2M)", "MNC": "-", "Propriedade": "+12 DMG, +2 CRG", "Gold": 1200},
        {"Tipo": "Adaga", "Subtipo": "Punhal", "DIF": "5 (1M)", "MNC": "-", "Propriedade": "+5 ICT", "Gold": 1000},
        {"Tipo": "Adaga", "Subtipo": "Katar", "DIF": "7 (1M)", "MNC": "-", "Propriedade": "+8 DMG, +6 CRG", "Gold": 1500},
        {"Tipo": "Arco", "Subtipo": "Curto", "DIF": "6 (2M)", "MNC": "Flecha", "Propriedade": "MNC máx X", "Gold": 1000},
        {"Tipo": "Arco", "Subtipo": "Longo", "DIF": "7 (2M)", "MNC": "Flecha", "Propriedade": "MNC máx X, +6 DMG", "Gold": 1300},
        {"Tipo": "Arco", "Subtipo": "Composto", "DIF": "8 (2M)", "MNC": "Flecha", "Propriedade": "MNC máx X, +8 DMG, +6 CRG", "Gold": 2000},
        {"Tipo": "Armas de Fogo", "Subtipo": "Revólver", "DIF": "6 (1M)", "MNC": "38 mm", "Propriedade": "MNC máx 8, +6 DMG", "Gold": 1000},
        {"Tipo": "Armas de Fogo", "Subtipo": "Bacamarte", "DIF": "7 (1M)", "MNC": "C1", "Propriedade": "MNC máx 4, +8 DMG", "Gold": 1500},
        {"Tipo": "Armas de Fogo", "Subtipo": "Espingarda", "DIF": "8 (1M) / 7 (2M)", "MNC": "C12", "Propriedade": "MNC máx 2, +12 DMG", "Gold": 1300},
        {"Tipo": "Armas de Fogo", "Subtipo": "Carabina", "DIF": "7 (2M)", "MNC": "22 mm", "Propriedade": "MNC máx 6, +10 DMG", "Gold": 1200},
        {"Tipo": "Armas de Fogo", "Subtipo": "Bazuca", "DIF": "8 (2M)", "MNC": "Míssil", "Propriedade": "MNC máx 1, +20 DMG", "Gold": 2000},
        {"Tipo": "Balista", "Subtipo": "Arbalesta", "DIF": "7 (2M)", "MNC": "Virote", "Propriedade": "MNC máx 3, +8 DMG", "Gold": 1100},
        {"Tipo": "Balista", "Subtipo": "Cerco", "DIF": "8 (2M)", "MNC": "Virote", "Propriedade": "MNC máx 1, +15 DMG", "Gold": 1300},
        {"Tipo": "Bastão", "Subtipo": "-", "DIF": "7 (2M)", "MNC": "-", "Propriedade": "Testes de Ataque (DES+BRI)", "Gold": 1000},
        {"Tipo": "Besta", "Subtipo": "-", "DIF": "6 (1M)", "MNC": "Dardo", "Propriedade": "MNC máx 12, +6 DMG", "Gold": 1800},
        {"Tipo": "Corrente", "Subtipo": "-", "DIF": "7 (2M)", "MNC": "-", "Propriedade": "+10 CRG", "Gold": 1100},
        {"Tipo": "Corrente", "Subtipo": "Kusarigama", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+12 DMG", "Gold": 1300},
        {"Tipo": "Espada", "Subtipo": "Gladius", "DIF": "6 (1M)", "MNC": "-", "Propriedade": "", "Gold": 1000},
        {"Tipo": "Espada", "Subtipo": "Claymore", "DIF": "9 (1M) / 7 (2M)", "MNC": "-", "Propriedade": "+6 DMG, +15 CRG", "Gold": 1300},
        {"Tipo": "Espada", "Subtipo": "Montante", "DIF": "6 (1M)", "MNC": "-", "Propriedade": "+20 DMG", "Gold": 1300},
        {"Tipo": "Espada", "Subtipo": "Florete", "DIF": "7 (1M)", "MNC": "-", "Propriedade": "+15 ICT", "Gold": 1500},
        {"Tipo": "Espada", "Subtipo": "Sabre", "DIF": "8 (1M) / 7 (2M)", "MNC": "-", "Propriedade": "+8 DMG, +4 CRG", "Gold": 1200},
        {"Tipo": "Espada", "Subtipo": "Jian", "DIF": "7 (1M)", "MNC": "-", "Propriedade": "+10 DMG", "Gold": 1300},
        {"Tipo": "Espada", "Subtipo": "Katana", "DIF": "7 (2M)", "MNC": "-", "Propriedade": "+6 DMG, +6 CRG", "Gold": 1400},
        {"Tipo": "Espada", "Subtipo": "Ninjato", "DIF": "7 (1M) / 6 (2M)", "MNC": "-", "Propriedade": "+8 CRG, 8 ICT", "Gold": 1400},
        {"Tipo": "Foice", "Subtipo": "Longa", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+20 DMG, +10 CRG", "Gold": 1600},
        {"Tipo": "Foice", "Subtipo": "Curta", "DIF": "6 (1M)", "MNC": "-", "Propriedade": "+10 DMG, +10 ICT", "Gold": 1600},
        {"Tipo": "Lança", "Subtipo": "Pique", "DIF": "6 (1M)", "MNC": "-", "Propriedade": "+5 ICT", "Gold": 1100},
        {"Tipo": "Lança", "Subtipo": "Tridente", "DIF": "8 (1M) / 7 (2M)", "MNC": "-", "Propriedade": "+12 DMG, +4 CRG", "Gold": 1600},
        {"Tipo": "Lança", "Subtipo": "Alabarda", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+15 DMG", "Gold": 1500},
        {"Tipo": "Machado", "Subtipo": "-", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+12 DMG", "Gold": 1200},
        {"Tipo": "Machado", "Subtipo": "Machadinha", "DIF": "6 (1M)", "MNC": "-", "Propriedade": "+5 DMG, +5 ICT", "Gold": 1500},
        {"Tipo": "Machado", "Subtipo": "Guerra", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+10 DMG", "Gold": 1400},
        {"Tipo": "Maça", "Subtipo": "Clava", "DIF": "7 (1M) / 6 (2M)", "MNC": "-", "Propriedade": "+10 DMG", "Gold": 1400},
        {"Tipo": "Maça", "Subtipo": "Mangual", "DIF": "7 (1M)", "MNC": "-", "Propriedade": "+15 DMG", "Gold": 1300},
        {"Tipo": "Manopla", "Subtipo": "-", "DIF": "7 (1M)", "MNC": "-", "Propriedade": "+6 DMG, +12 CRG", "Gold": 2000},
        {"Tipo": "Martelo", "Subtipo": "-", "DIF": "8 (1M) / 7 (2M)", "MNC": "-", "Propriedade": "+5 DMG, +5 ICT", "Gold": 1400},
        {"Tipo": "Martelo", "Subtipo": "Marreta", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+10 DMG, +6 CRG", "Gold": 1500},
        {"Tipo": "Martelo", "Subtipo": "Picareta", "DIF": "8 (2M)", "MNC": "-", "Propriedade": "+6 DMG", "Gold": 1700}
    ]
};